server:
  port: 5421
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/val
    username: ajay
    password: Ajay@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
